### ISSUE TITLE
Forks from original source

### ISSUE THREAD

**Issue by Neustradamus** [DamianoP/uvncrep017-ws#2]
3 forks from original source "http://koti.mbnet.fi/jtko/uvncrepeater/":
- https://github.com/tenchman/uvncrepeater-ac + forks: https://github.com/stefanklug/uvncrepeater + https://github.com/eway-crm/uvncrepeater-ac
- https://github.com/qian-jiahong/uvncrep017-ws + fork: https://github.com/DamianoP/uvncrep017-ws
- https://github.com/noperfects/vnc_repeater_linux

**Comment by Neustradamus** [comment]
@DamianoP: Can you merge improvements?

**Comment by DamianoP** [comment]
in the future if I have more time I will do it, at the moment I don't have a moment's break
